Modified lesson3.exercise1
artpetrovskii/Basics-Python-Course pull request #16
Opened 2020-07-09 10:54 UTC by artpetrovskii

2020-07-10 05:25 UTC, apetrovskiy requested changes

2020-07-10 05:25 UTC, apetrovskiy commented on lesson 3. exercise 1.py
> +    import random
It doesn't even work:
```  File "C:/Projects/Python/Basics-Python-Course/lesson 3. exercise 1.py", line 1
    import random
    ^
IndentationError: unexpected indent

2020-07-11 05:58 UTC, apetrovskiy requested changes

2020-07-11 05:58 UTC, apetrovskiy commented on lesson 3. exercise 1.py
> -def game():
Now the program works differently, how will you merge the past and the current versions?

2020-07-11 05:58 UTC, apetrovskiy commented on lesson 3. exercise 1.py
> +        is_repeat = True
It works the wrong way:
```Задумайте любое число от 1 до 100 и запишите его на бумаге. 
 Как будете готовы, нажмите 'ввод'
Ммм... может 62 загаданное число?
1: Ты угадал! 5: Недобор! 9: Перебор!
5
Ну как так
Я предположу, что вы загадали 89?
1: Ты угадал! 5: Недобор! 9: Перебор!
5
Черт
Ммм... может 100 загаданное число?
1: Ты угадал! 5: Недобор! 9: Перебор!
5
О нет
Ненавижу тебя!

2020-07-14 12:21 UTC, artpetrovskii commented on lesson 3. exercise 1.py
> +        is_repeat = True
I fixed this problem

2020-07-18 10:54 UTC, apetrovskiy commented on lesson 3. exercise 1.py
> +    begin = 1
![image](https://user-images.githubusercontent.com/2947151/87851102-2965b080-c8fe-11ea-9e78-723eaa2a6bd9.png)

2020-07-18 11:26 UTC, apetrovskiy approved these changes

2020-07-18 12:09 UTC, merged